Controllers/CommentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoreDemo.Controllers
{
    [AllowAnonymous]
    public class CommentController : Controller
    {
        CommentManager cm = new CommentManager(new EfCommentRepository());

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult PartialAddComment()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult PartialAddComment(Comment comment)
        {
            comment.CommentDate=DateTime.Parse(DateTime.Now.ToShortDateString());
            comment.CommentStatus = true;
            comment.BlogId = 1;
            cm.CommentAdd(comment);
            return PartialView();
        }

        public PartialViewResult CommentListByBlog(int id)
        {
            var values = cm.GetList(id);
            return PartialView(values);
        }

    }
}

Views/Comment/CommentListByBlog.cshtml
@model IEnumerable<EntityLayer.Concrete.Comment>

<div class="comment-top">
    <h4>Yorumlar</h4>
    <div class="media">
        <img src="~/webTema/images/t1.jpg" alt="" class="img-fluid" />
        <div class="media-body">
            <h5 class="mt-0">Joseph Goh</h5>
            <p>
                Lorem Ipsum convallis diam consequat magna vulputate malesuada. id dignissim sapien velit id felis ac cursus eros.
                Cras a ornare elit.
            </p>

            <div class="media mt-3">
                <a class="d-flex pr-3" href="#">
                    <img src="images/t2.jpg" alt="" class="img-fluid" />
                </a>
                <div class="media-body">
                    <h5 class="mt-0">Richard Spark</h5>
                    <p>
                        Lorem Ipsum convallis diam consequat magna vulputate malesuada. id dignissim sapien velit id felis ac cursus eros.
                        Cras a ornare elit.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Comment/PartialAddComment.cshtml
<div class="comment-top">
    <h4>Bir yorum bırakın</h4>
    <div class="comment-bottom">
        <form method="post" asp-action="PartialAddComment" asp-controller="Comment">
            <input class="form-control" type="text" id="CommentUserName" name="CommentUserName" placeholder="Adınız Soyadınız" required="">

            <input class="form-control" type="text" id="CommentTitle" name="CommentTitle" placeholder="konu" required="">

            <textarea class="form-control" id="CommentContent" name="CommentContent" placeholder="Yorumunuz..." required=""></textarea>

            <button type="button" onclick="sendComment()" class="btn btn-primary submit">Yorum yap</button>
        </form>
    </div>
</div>
<script>
    function sendComment() {
        var nameAndSurname = $("#CommentUserName").val();
        var commentTitle = $("#CommentTitle").val();
        var comment = $("#CommentContent").val();

        $.ajax({
            method: "post",
            url: "/Comment/PartialAddComment/",
            data: {
                CommentUserName: nameAndSurname,
                CommentTitle: commentTitle,
                CommentContent: comment
            }
        }).done(function (result) {
            if (result.hasError != undefined && result.hasError) {
                alert("Yorumunuz eklenmedi. Bir hata oluştu");
            }
            location.reload();
        }).fail(function () {

            alert("Yorumunuz eklenmedi. Bir hata oluştu");

        })
    }

</script>