Controllers/MessageController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreDemo.Controllers
{
    [AllowAnonymous]
    public class MessageController : Controller
    {
        Message2Manager message2Manager = new Message2Manager(new EfMessage2Repository());
        Context context = new Context();
        public IActionResult InBox()
        {

            var username = User.Identity.Name;
            var usermail = context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerId = context.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriteId).FirstOrDefault();
            var values = message2Manager.GetInBoxListByWriter(writerId);
            return View(values);
        }

        public IActionResult SendBox()
        {

            var username = User.Identity.Name;
            var usermail = context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerId = context.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriteId).FirstOrDefault();
            var values = message2Manager.GetSendBoxListByWriter(writerId);
            return View(values);
        }

        public IActionResult MessageDetails(int id)
        {
            var value = message2Manager.TGetById(id);
            return View(value);
        }

        [HttpGet]
        public IActionResult SendMessage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SendMessage(Message2 message2)
        {
            var username = User.Identity.Name;
            var usermail = context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerId = context.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriteId).FirstOrDefault();
            message2.SenderId = writerId;
            message2.ReceiverId = 3;
            message2.Status = true;
            message2.Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            message2Manager.Add(message2);
            return RedirectToAction("Inbox");
        }
    }
}

Views/Message/InBox.cshtml
@model List<Message2>
@{
    ViewData["Title"] = "InBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">

<h1>Gelen Kutusu</h1>

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Gönderen</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>@item.Id</th>
            <td>@item.Subject</td>
            <td>@item.SenderUser.WriteName</td>
            <td>@(((DateTime)item.Date).ToString("dd-MM-yyyy"))</td>
            <td>
                <a href="/message/messagedetails/@item.Id" title="Mesajı Aç" class="btn btn-primary btn-sm">
                    <i class="fa-solid fa-envelope-open-text"></i>
                </a>
            </td>
        </tr>
    }
</table>
<a href="/Message/SendMessage/" class="btn btn-primary">Yeni Mesaj Oluştur</a>

Views/Message/MessageDetails.cshtml
@model EntityLayer.Concrete.Message2

@{
    ViewData["Title"] = "MessageDetails";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Mesaj Detay Sayfası</h1>

<br />

@Html.Label("Mesaj ID")
@Html.TextBoxFor(x=>x.Id, new{@class="form-control",@readonly="readonly"})
<br />
@Html.Label("Mesaj Başlığı")
@Html.TextBoxFor(x=>x.Subject, new{@class="form-control",@readonly="readonly"})
<br />
@Html.Label("Mesaj İçeriği")
@Html.TextAreaFor(x=>x.Details,10,3, new{@class="form-control",@readonly="readonly"})
<br />
<a href="/message/inbox/" class="btn btn-success" >Mesajlara Dön</a>

Views/Message/SendBox.cshtml
@model List<Message2>
@{
    ViewData["Title"] = "SendBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">

<h1>Giden Kutusu</h1>

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>@item.Id</th>
            <td>@item.Subject</td>
            <td>@item.ReceiverUser.WriteName</td>
            <td>@(((DateTime)item.Date).ToString("dd-MM-yyyy"))</td>
            <td>
                <a href="/message/messagedetails/@item.Id" title="Mesajı Aç" class="btn btn-primary btn-sm">
                    <i class="fa-solid fa-envelope-open-text"></i>
                </a>
            </td>
        </tr>
    }
</table>
<a href="/Message/SendMessage/" class="btn btn-primary">Yeni Mesaj Oluştur</a>

Views/Message/SendMessage.cshtml
@model EntityLayer.Concrete.Message2
@{
    ViewData["Title"] = "SendMessage";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Yeni Mesaj Oluşturma</h1>
<br />
@using (Html.BeginForm("SendMessage", "Message", FormMethod.Post))
{
    @Html.Label("Alıcı")
    @*@Html.TextBoxFor(x=>x.Subject,new{@class="form-control"})*@
    <input type="text" class="form-control" />
    <br />
    @Html.Label("Konu")
    @Html.TextBoxFor(x=>x.Subject,new{@class="form-control"})
    <br />
    @Html.Label("Mesajınız")
    @Html.TextBoxFor(x=>x.Details,new{@class="form-control"})
    <br />
    <button class="btn btn-primary">Mesajı Gönder</button>
}